services:
  setup:
    profiles:
      - setup
    build:
      context: ELK/setup/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    init: true
    # バインドマウント削除 - ビルド時にファイルをコピーするように変更
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD:-}
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-}
    networks:
      - elk
    depends_on:
      - elasticsearch

  elasticsearch:
    build:
      context: ELK/elasticsearch/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    volumes:
      # 設定ファイルのバインドマウントを削除
      - elasticsearch:/usr/share/elasticsearch/data:Z
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      node.name: elasticsearch
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      discovery.type: single-node
    networks:
      - elk
    restart: unless-stopped

  logstash:
    build:
      context: ELK/logstash/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    # バインドマウントを削除
    ports:
      - "50000:50000"
    environment:
      LS_JAVA_OPTS: "-Xms256m -Xmx512m -XX:+HeapDumpOnOutOfMemoryError"
      LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD:-}
    networks:
      - elk
      - app-network
    depends_on:
      - elasticsearch
    restart: unless-stopped

  kibana:
    build:
      context: ELK/kibana/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    # バインドマウントを削除
    ports:
      - 5601:5601
    environment:
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-}
    networks:
      - elk
    depends_on:
      - elasticsearch
    restart: unless-stopped

networks:
  elk:
    driver: bridge
  app-network:
    name: ft_transcendence_app-network
    external: true

volumes:
  elasticsearch:
  # 必要に応じて他のボリュームを追加