# Generated by Django 5.1.6 on 2025-02-17 03:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pong", "0006_user_language"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tournament",
            name="games",
        ),
        migrations.RemoveField(
            model_name="tournament",
            name="participants",
        ),
        migrations.DeleteModel(
            name="BlockchainScore",
        ),
        migrations.DeleteModel(
            name="Tournament",
        ),
    ]
