# Generated by Django 5.1.6 on 2025-02-19 01:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pong", "0009_tournamentgamesession_tournamentmatch_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tournamentgamesession",
            name="max_players",
        ),
        migrations.RemoveField(
            model_name="tournamentgamesession",
            name="min_players",
        ),
        migrations.AlterField(
            model_name="tournamentgamesession",
            name="status",
            field=models.CharField(
                choices=[
                    ("WAITING_PLAYERS", "Waiting for Players"),
                    ("IN_PROGRESS", "Tournament in Progress"),
                    ("COMPLETED", "Tournament Completed"),
                    ("CANCELLED", "Tournament Cancelled"),
                ],
                default="WAITING_PLAYERS",
                max_length=20,
            ),
        ),
    ]
